# Generated by Django 4.1.5 on 2023-02-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdata",
            name="data",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="formdata",
            name="hora_transacao",
            field=models.CharField(max_length=8),
        ),
    ]
