# Generated by Django 4.1.5 on 2023-02-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0002_alter_formdata_data_alter_formdata_hora_transacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdata",
            name="valor",
            field=models.IntegerField(),
        ),
    ]
